config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'relationships/create'
  get 'relationships/destroy'
    root to: "toppages#index"
    
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get 'memos/new', to: "memos#new"
  post 'memos/create'
  get 'memos/destroy'
  get 'memos/:id', to: 'memos#show'

  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :memos, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :memo
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  # favorite のコード
  has_many :reverses_of_favorite, class_name: "Favorite"
  has_many :favoriters, through: :reverses_of_favorite, source: :user
  has_many:favorites, dependent: :destroy
  # favorite のコード終了
  
  validates :title, presence: true, length: { maximum: 20 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
  #followの存在しないクラスを参照することを防ぐため。
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :memos
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow #この行が多対多の関係を作っている
  has_many :reverses_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverses_of_relationship, source: :user #この行が多対多の関係を作っている
# favorite のコード
    has_many :favorites
    has_many :likes, through: :favorites, source: :memo
# favorite のコード終了
  
  
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_memos
    Memo.where(user_id: self.following_ids + [self.id])
  end
  
  def favorite(other_memo)
    unless self == other_memo
      self.favorites.find_or_create_by(memo_id: other_memo.id)
    end
  end
  
  def unfavorite(other_memo)
    favorite = self.favorites.find_by(memo_id: other_memo.id)
    favorite.destroy if favorite
  end
  
  def likes?(other_memo)
    self.likes.include?(other_memo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  
private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_memos = user.memos.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_likes = user.likes.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    memo = Memo.find(params[:memo_id])
    current_user.favorite(memo)
    flash[:success] = "メモをお気に入りしました。"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    memo = Memo.find(params[:memo_id])
    current_user.unfavorite(memo)
    flash[:success] = "メモのお気に入りを解除しました。"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def new
    @memo = Memo.new
  end

  def create
    @memo = current_user.memos.build(memo_params)
    if @memo.save
      flash[:success] = "メモを投稿しました"
      redirect_to root_url
    else
      @memos = current_user.feed_memos.order(id: :desc).page(params[:page])
      flash.now[:danger] = "メモの送信に失敗しました"
      render "toppages/index"
    end
  end

  def destroy
    @memo.destroy
    flash[:success] = "メモを削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  def show
    @memo = Memo.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:title, :fact, :abstract, :diversion, :wrap)
  end
  
  def correct_user
    @memo = current_user.memos.find_by(id: params[:id])
    unless @memo
    redirect_to root_url
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = "ユーザーをフォローしました"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = "ユーザーのフォローを解除しました。"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "ログインに成功しました"
      redirect_to root_url
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    #↓はメールアドレスとパスワードがあっていないとtrueにならないということ。
    if @user && @user.authenticate(password)
      #ログイン成功
      session[:user_id] = @user.id
      return true
    else
      #ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    if logged_in?
      @memo = current_user.memos.build #form_with用
      @memos = current_user.feed_memos.order(id: :desc).page(params[:page])
      #memosはトップページにmemo一覧を作るため
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :likes]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @memos = @user.memos.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザーを登録しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました。"
      render :new
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    #これでログインしていないと見えないよをしてくれる
    def current_user
        @current ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
      !!current_user
    end    
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end   
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.likes?(memo) %>

<%= form_with(model: current_user.favorites.find_by(memo_id: memo.id), local: true, method: :delete) do |f| %>
<%= hidden_field_tag :memo_id, memo.id %>

<%= button_tag type: 'submit', class: "btn btn-link text-secondary" do %>
  <i class="fas fa-heart-broken "></i>
<% end %>
<% end %>
<% else %>

<%= form_with(model: current_user.favorites.build, local: true) do |f| %>

<%= hidden_field_tag :memo_id, memo.id %>

<%= button_tag type: 'submit', class: "btn btn-link text-secondary" do %>
    <i class="fas fa-heart"></i>
<% end %>

<% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

  <div id="error_explanation" crass="alert alert-carning">
      <ul class="mb-0">
          <% model.errors.full_messages.each do |message| %>
          <li>
              <%= message %>
          </li>
          <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-
<%= message_type %>
">
<%= message %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
    <!-- Bootstrap CSS -->
    <title>メモの魔力</title>

<%= csrf_meta_tags %>

    
<%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
<%= yield %>

    </div>
    
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>

  </body>
</html>

app/views/memos/_memos.html.erb
<ul class="list-unstyled">
  <% memos.each do |memo| %>
    <li class="media mb-3">
        <img class="mr-2 rounded-circle" src="<%= gravatar_url(memo.user, { size: 50 }) %>" alt="">
        <div class="medeia-body">
            <div>
                  <%= link_to memo.user.name, user_path(memo.user), class: "text-dark" %>
                <span class="text-muted"><%= memo.created_at.strftime('%Y/%m/%d') %></span>
              <div>
                <%= link_to memo.title, memo %>
                <% if current_user == memo.user %>

                <%= link_to memo, method: :delete, data: { confirm: "You sure?" }, class: "text-decoration-none" do %>
                 <i class="far fa-trash-alt my-gray text-decoration-none fa-fw"></i>
                <% end %>
                 <% end %>

                
            <div class="yokonarabi">
            <%= render "favorites/favorite_button", memo: memo %>
            </div>
        </div>
    </li>
  <% end %>
  <%= paginate memos %>
</ul>

app/views/memos/create.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= form_with(model: @memo, local: true) do |f| %>

  
<%= f.label :title, 'メッセージ' %>

  
<%= f.text_field :title %>


  
<%= f.submit '投稿' %>

<% end %>


<%= link_to '一覧に戻る', memos_path %>

app/views/memos/new.html.erb
    <div class="mt-2">
      <script>
      var today=new Date(); 

//年・月・日・曜日を取得
var year = today.getFullYear();
var month = today.getMonth()+1;
var week = today.getDay();
var day = today.getDate();

//年・月・日・曜日を書き出す
document.write(year+"年"+month+"月"+day+"日 ");
    </script>
</div>
<%= form_with(model: @memo, local: true) do |f| %>

<div class="row">
  <div class="col-6">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, size: "40x1" %>
  </div>
</div>

<div class="row">
  <div class="col-2">     
<%= f.label :wrap, '要約' %>
<%= f.text_area :wrap, size: "1x20", class: "form-control" %>
  </div>
  <div class="col-4">    
  <%= f.label :fact, '事実' %>
  <%= f.text_area :fact, size: "1x20", class: "form-control" %>
  </div>
  <div class="col-3">
<%= f.label :abstract, '抽象化' %>
<%= f.text_area :abstract, size: "1x20", class: "form-control" %>
  </div>
  <div class="col-3">
<%= f.label :diversion, '転用' %>
<%= f.text_area :diversion, size: "1x20", class: "form-control" %>  
  </div>
</div>

<div class="row">
  <div class="col-3">
<%= link_to root_path, class: "btn btn-link text-secondary" do %>
<i class="fas fa-undo fa-rotate-270 fa-3x"></i>
<% end %>
  </div>
  
  <div class="offset-8 col-1">
<%= button_tag type: 'submit', class: "btn btn-link text-secondary" do %>
<i class="fas fa-pencil-alt fa-rotate-270 fa-3x"></i>
<% end %>
  </div>
</div>

<% end %>

app/views/memos/show.html.erb
<%= form_with(model: @memo, local: true) do |f| %>
<%= @memo.created_at.strftime('%Y/%m/%d') %>


<div class="row">
  <div class="col-6">
    <textarea disabled rows=1 cols=40>
<%= @memo.title %>
    </textarea>
  </div>
</div>

<div class="row">
  <div class="col-2">     
<%= f.label :wrap, '要約' %>
    <textarea disabled rows=20 cols=20>
<%= @memo.wrap %>
    </textarea>
    </div>
    
  <div class="col-4">    
  <%= f.label :fact, '事実' %>
    <textarea disabled rows=20 cols=40>
<%= @memo.fact %>
    </textarea>
    </div>
    
  <div class="col-3">
<%= f.label :abstract, '抽象化' %>
    <textarea disabled rows=20 cols=30>
<%= @memo.abstract %>
    </textarea>
    </div>
  
  <div class="col-3">
<%= f.label :diversion, '転用' %>
    <textarea disabled rows=20 cols=30>
<%= @memo.diversion %>
    </textarea>
    </div>
</div>

<% end %>

<div class="row">
  <div class="col-3">
<%= link_to '一覧に戻る', root_path %>
  </div>
  
  <div class="offset-7 col-2">
<%= render "favorites/favorite_button", memo: @memo %>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>

  <% if current_user.following?(user) %>
<!-- ここからアンフォローボタンになる -->
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
<%= button_tag type: 'submit', class: "btn btn-link text-secondary" do %>
<i class="fas fa-user-minus"></i>
    <% end %>
    <% end %>
<!-- ここまでがアンフォローボタンになる -->
  <% else %>
  <!-- ここからフォローボタンになる -->
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
<%= button_tag type: 'submit', class: "btn btn-link text-secondary" do %>
<i class="fas fa-user-plus"></i>
    <% end %>
    <% end %>
<!-- ここまでがフォローボタンになる -->
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>


<div class="row">
  <aside class="col-sm-2">
<%= render 'users/aside' %>
  </aside>
  <div class="col-sm-10">
    <div class="f-container">
      <div class="mr-4">
        <img class="rounded-circle img-fluid" src="<%= gravatar_url(current_user, { size: 120 }) %>" alt="">
      </div>
      <div class="left">
        <h1>Let's try memo
          <span>
            <%= link_to memos_new_path do %>
            <span class="pencil-alt 2x my-gray">
              <%= fa_icon("pencil-alt") %>
            </span>
          <% end %>
          </span>
        </h1>
      </div>
    </div>
    
    <div class="siinas">
      <%= current_user.name %>
    </div>
  <%= render "memos/memos", memos: @memos %>
  </div>
</div>
<% else %>

  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      
<%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>

    </div>
  </div>
<% end %>

app/views/users/_aside.html.erb
  <ul class="nav flex-column" style="list-style: none;">
    <li class="nav-item">
<!-- これがTOPボタン -->
<%= link_to root_path do %>
<div class="home 2x my-gray">
<%= fa_icon("home 2x") %>
</div>
<% end %>    
    </li>
    <li class="nav-item">
<!-- これがユーザー一覧ボタン -->
<%= link_to users_path do %>
<div class="users 2x my-gray">
<%= fa_icon("users 2x") %>
</div>
<% end %>
    </li>
    <li class="nav-item">
<!-- これが新規メモ作成画面ボタン -->
<%= link_to memos_new_path do %>
<div class="pencil-alt 2x my-gray">
<%= fa_icon("pencil-alt 2x") %>
</div>
<% end %>
    </li>
    <li class="nav-item">
<!-- これがお気に入りメモ一覧ボタン -->
<%= link_to likes_user_path(current_user) do %>
<div class="heart 2x my-gray">
<%= fa_icon("heart 2x") %>
</div>
<% end %>
    </li>
    <li class="nav-item">
<!-- これがログアウトボタン -->
<%= link_to logout_path, method: :delete do %></li>
<div class="walking 2x my-gray">
<%= fa_icon("walking 2x") %>
</div>
<% end %>
  </ul>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="rounded-circle" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="col-md">
          <div class="media-body">

            <div>
<%= link_to user.name, user_path(user) %>
<%= render "relationships/follow_button", user: user %>
            </div>
          </div>
        </div>  
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-sm-4">

      <div class="card-body">
        <img class="rounded-circle" src="
<%= gravatar_url(@user, { size: 100 }) %>
" alt="">
      </div>

    
  </aside>
  <h2><%= @user.name %></h2>
  
  
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link 
<%= 'active' if current_page?(user_path(@user)) %>
">Memos  <span class="badge badge-secondary">
<%= @count_memos %></span></a></li>
      <li class="nav-item"><a href="#" class="nav-link">いいね！</a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>"フォロー中 <span class ="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>"フォロワー <span class="badge badge-secondary"><%= @count_followers %></a></li>
    </ul>
    
<%= render "users", users: @followers %>    

  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
   <aside class="col-sm-2">
<%= render 'aside' %>
  </aside>
  <div class="col-sm-10">
     <div>
    <img class="rounded-circle img-fluid" src="
<%= gravatar_url(current_user, { size: 100 }) %>
" alt=""><p>Let's try memo</p>
<%= link_to "✏︎︎", memos_new_path %>
     </div>
       <p><%= current_user.name %></p>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link 
<%= 'active' if current_page?(user_path(@user)) %>
">Memos  <span class="badge badge-secondary">
<%= @count_memos %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>">お気に入り一覧 <span class ="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー中 <span class ="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    
<%= render 'users', users: @followings %>

  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <aside class="col-sm-2">
<%= render 'aside' %>
  </aside>
  
  <div class="col-sm-10">
     <div>
    <img class="rounded-circle img-fluid" src="
<%= gravatar_url(current_user, { size: 100 }) %>
" alt=""><p>Let's try memo</p>
<%= link_to "✏︎︎", memos_new_path %>
     </div>
       <p><%= current_user.name %></p>

      <%= render 'users', users: @users %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="row">
   <aside class="col-sm-2">
<%= render 'aside' %>
  </aside>
  
  <div class="col-sm-10">
     <div>
    <img class="rounded-circle img-fluid" src="
<%= gravatar_url(current_user, { size: 100 }) %>
" alt=""><p>Let's try memo</p>
<%= link_to "✏︎︎", memos_new_path %>
     </div>
       <p><%= current_user.name %></p>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link 
<%= 'active' if current_page?(user_path(@user)) %>
">Memos  <span class="badge badge-secondary">
<%= @count_memos %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>">お気に入り一覧 <span class ="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー中 <span class ="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    
<%= render "memos/memos", memos: @likes %>    

  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Thank you memo!</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    
<%= form_with(model: @user, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<!-- renderを入れたことでエラーメッセージが追加された -->

<!-- Name新規登録箇所 -->

      <div class="form-group">
        <div class="cp_iptxt">
	        <input class="ef" type="text" name="user[name]" id="user_name" >
	        <label>Name</label>
	        <span class="focus_line"></span>
        </div>
      </div>
<!-- Name新規登録箇所ここまで -->
<!-- Email新規登録箇所 -->

      <div class="form-group">
        <div class="cp_iptxt">
	        <input class="ef" type="text" name="user[email]" id="user_email" >
	        <label>Email</label>
	        <span class="focus_line"></span>
        </div>
      </div>
      
<!-- Email新規登録箇所ここまで -->

<!-- password新規登録箇所 -->

      <div class="form-group">

        <div class="cp_iptxt">
	        <input class="ef" type="password" name="user[password]" id="user_password" >
	        <label>Password</label>
	        <span class="focus_line"></span>
        </div>
        
      </div>

<!-- password新規登録箇所ここまで -->

<!-- 確認password新規登録箇所 -->

      <div class="form-group">

        <div class="cp_iptxt">
	        <input class="ef" type="password" name="user[password_confirmation]" id="password_confirmation" >
	        <label>Confirmation</label>
	        <span class="focus_line"></span>
        </div>
        
      </div>
      
<!-- 確認password新規登録箇所ここまで -->
 <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
 <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
   <aside class="col-sm-2">
<%= render 'aside' %>
  </aside>
  <div class="col-sm-10">
     <div>
    <img class="rounded-circle img-fluid" src="
<%= gravatar_url(@user, { size: 100 }) %>
" alt=""><p>Let's try memo</p>
<%= link_to "✏︎︎", memos_new_path %>
     </div>
       <p><%= @user.name %></p>
       
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link 
<%= 'active' if current_page?(user_path(@user)) %>
">Memos  <span class="badge badge-secondary">
<%= @count_memos %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>">お気に入り一覧 <span class ="badge badge-secondary"><%= @count_likes %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー中 <span class ="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    
<%= render "memos/memos", memos: @memos %>    

  </div>
</div>